-- Sample data for Product table
INSERT INTO product (name, description, price, stock, category, created_at) VALUES
('Laptop Pro 15', 'High-performance laptop for professionals', 1299.99, 50, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Wireless Mouse', 'Ergonomic wireless mouse with USB receiver', 29.99, 200, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Mechanical Keyboard', 'RGB mechanical gaming keyboard', 89.99, 75, 'ELECTRONICS', CURRENT_TIMESTAMP),
('USB-C Hub', '7-in-1 USB-C hub adapter', 49.99, 120, 'ELECTRONICS', CURRENT_TIMESTAMP),
('27" Monitor 4K', 'Ultra HD 27-inch monitor with HDR', 399.99, 30, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Bluetooth Headphones', 'Noise-cancelling over-ear headphones', 159.99, 80, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Smartphone Stand', 'Adjustable phone stand for desk', 19.99, 250, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Webcam HD 1080p', 'Full HD webcam with microphone', 79.99, 100, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Power Bank 20000', 'Portable charger 20000mAh', 39.99, 150, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Wireless Charger', 'Fast wireless charging pad', 24.99, 180, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Cotton T-Shirt', '100% cotton basic t-shirt', 14.99, 500, 'CLOTHING', CURRENT_TIMESTAMP),
('Jeans Slim Fit', 'Classic slim fit denim jeans', 49.99, 200, 'CLOTHING', CURRENT_TIMESTAMP),
('Hoodie Fleece', 'Comfortable fleece hoodie', 39.99, 150, 'CLOTHING', CURRENT_TIMESTAMP),
('Running Shoes', 'Lightweight running sneakers', 79.99, 100, 'CLOTHING', CURRENT_TIMESTAMP),
('Winter Jacket', 'Waterproof winter jacket', 129.99, 80, 'CLOTHING', CURRENT_TIMESTAMP),
('Summer Dress', 'Light floral summer dress', 34.99, 120, 'CLOTHING', CURRENT_TIMESTAMP),
('Leather Belt', 'Genuine leather belt', 24.99, 300, 'CLOTHING', CURRENT_TIMESTAMP),
('Wool Socks (3pc)', 'Merino wool socks pack', 19.99, 250, 'CLOTHING', CURRENT_TIMESTAMP),
('Baseball Cap', 'Adjustable cotton cap', 16.99, 200, 'CLOTHING', CURRENT_TIMESTAMP),
('Backpack Nylon', 'Water-resistant nylon backpack', 44.99, 90, 'CLOTHING', CURRENT_TIMESTAMP),
('Organic Coffee 500g', 'Fair trade organic coffee beans', 12.99, 300, 'FOOD', CURRENT_TIMESTAMP),
('Green Tea Box', 'Japanese green tea 100 bags', 18.99, 200, 'FOOD', CURRENT_TIMESTAMP),
('Olive Oil 1L', 'Extra virgin olive oil', 22.99, 150, 'FOOD', CURRENT_TIMESTAMP),
('Honey 500g', 'Natural acacia honey', 15.99, 180, 'FOOD', CURRENT_TIMESTAMP),
('Pasta Pack 1kg', 'Italian durum wheat pasta', 4.99, 400, 'FOOD', CURRENT_TIMESTAMP),
('Tomato Sauce', 'Organic tomato sauce 500g', 3.99, 350, 'FOOD', CURRENT_TIMESTAMP),
('Dark Chocolate', '70% cocoa dark chocolate', 6.99, 250, 'FOOD', CURRENT_TIMESTAMP),
('Almonds 500g', 'Roasted almonds with sea salt', 14.99, 200, 'FOOD', CURRENT_TIMESTAMP),
('Protein Bars', 'Box of 12 protein bars', 29.99, 120, 'FOOD', CURRENT_TIMESTAMP),
('Sparkling Water', 'Mineral water 12x1.5L', 9.99, 200, 'FOOD', CURRENT_TIMESTAMP),
('Java Programming Book', 'Complete Java guide for beginners', 44.99, 100, 'BOOKS', CURRENT_TIMESTAMP),
('Sci-Fi Novel', 'Best-selling science fiction novel', 16.99, 200, 'BOOKS', CURRENT_TIMESTAMP),
('Cooking Recipes', 'International cuisine cookbook', 24.99, 150, 'BOOKS', CURRENT_TIMESTAMP),
('History Encyclopedia', 'World history comprehensive guide', 59.99, 80, 'BOOKS', CURRENT_TIMESTAMP),
('Self-Help Book', 'Personal development strategies', 19.99, 180, 'BOOKS', CURRENT_TIMESTAMP),
('Comic Book Vol.1', 'Graphic novel collection', 14.99, 120, 'BOOKS', CURRENT_TIMESTAMP),
('Poetry Anthology', 'Classic poetry collection', 12.99, 90, 'BOOKS', CURRENT_TIMESTAMP),
('Business Strategy', 'MBA business strategies book', 34.99, 100, 'BOOKS', CURRENT_TIMESTAMP),
('Art History Book', 'Renaissance art masterpiece guide', 49.99, 70, 'BOOKS', CURRENT_TIMESTAMP),
('Children Story Book', 'Illustrated bedtime stories', 11.99, 150, 'BOOKS', CURRENT_TIMESTAMP),
('LED Desk Lamp', 'Adjustable LED desk lamp', 34.99, 130, 'OTHER', CURRENT_TIMESTAMP),
('Yoga Mat Premium', 'Non-slip yoga mat 6mm', 29.99, 200, 'OTHER', CURRENT_TIMESTAMP),
('Plant Pot Ceramic', 'Modern ceramic plant pot', 18.99, 150, 'OTHER', CURRENT_TIMESTAMP),
('Tool Set Basic', '30-piece home tool kit', 59.99, 80, 'OTHER', CURRENT_TIMESTAMP),
('Pillow Memory Foam', 'Orthopedic memory foam pillow', 39.99, 120, 'OTHER', CURRENT_TIMESTAMP),
('Shower Curtain', 'Waterproof fabric shower curtain', 19.99, 180, 'OTHER', CURRENT_TIMESTAMP),
('Laundry Hamper', 'Collapsible laundry basket', 24.99, 100, 'OTHER', CURRENT_TIMESTAMP),
('Cutting Board Set', 'Bamboo cutting boards set', 29.99, 140, 'OTHER', CURRENT_TIMESTAMP),
('Travel Pillow', 'Neck support travel pillow', 16.99, 160, 'OTHER', CURRENT_TIMESTAMP),
('Picture Frame A4', 'Wooden picture frame set', 21.99, 200, 'OTHER', CURRENT_TIMESTAMP),
('Gaming Mouse RGB', 'High-DPI gaming mouse', 59.99, 90, 'ELECTRONICS', CURRENT_TIMESTAMP),
('SSD 1TB NVMe', 'Internal solid state drive', 119.99, 70, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Graphics Card RTX', 'High-performance GPU for gaming', 699.99, 20, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Router WiFi 6', 'Dual-band WiFi 6 router', 149.99, 60, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Smart Watch', 'Fitness tracking smartwatch', 199.99, 50, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Tablet 10 inch', 'Android tablet for productivity', 299.99, 40, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Action Camera 4K', 'Waterproof action camera', 249.99, 45, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Portable Speaker', 'Bluetooth portable speaker', 69.99, 110, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Car Mount Phone', 'Magnetic car phone holder', 14.99, 220, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Cable Organizer', 'Cable management clips set', 9.99, 280, 'ELECTRONICS', CURRENT_TIMESTAMP),
('Denim Shorts', 'Classic denim summer shorts', 34.99, 180, 'CLOTHING', CURRENT_TIMESTAMP),
('Polo Shirt', 'Cotton pique polo shirt', 29.99, 160, 'CLOTHING', CURRENT_TIMESTAMP),
('Cardigan Sweater', 'Lightweight cotton cardigan', 44.99, 100, 'CLOTHING', CURRENT_TIMESTAMP),
('Swim Trunks', 'Quick-dry swim shorts', 24.99, 120, 'CLOTHING', CURRENT_TIMESTAMP),
('Scarf Wool', 'Warm winter scarf', 19.99, 140, 'CLOTHING', CURRENT_TIMESTAMP),
('Gloves Leather', 'Genuine leather driving gloves', 29.99, 90, 'CLOTHING', CURRENT_TIMESTAMP),
('Sunglasses UV', 'Polarized UV protection sunglasses', 39.99, 110, 'CLOTHING', CURRENT_TIMESTAMP),
('Wallet Bi-Fold', 'Slim leather bi-fold wallet', 34.99, 130, 'CLOTHING', CURRENT_TIMESTAMP),
('Sneakers Canvas', 'Classic canvas sneakers', 49.99, 140, 'CLOTHING', CURRENT_TIMESTAMP),
('Raincoat Compact', 'Packable raincoat', 54.99, 80, 'CLOTHING', CURRENT_TIMESTAMP),
('Rice Basmati 2kg', 'Premium aged basmati rice', 8.99, 250, 'FOOD', CURRENT_TIMESTAMP),
('Coconut Milk 1L', 'Natural coconut milk', 3.49, 300, 'FOOD', CURRENT_TIMESTAMP),
('Chili Sauce', 'Spicy chili sauce 250ml', 4.99, 220, 'FOOD', CURRENT_TIMESTAMP),
('Herbs de Provence', 'Dried herbs blend 50g', 5.99, 180, 'FOOD', CURRENT_TIMESTAMP),
('Maple Syrup 500ml', 'Pure Canadian maple syrup', 14.99, 120, 'FOOD', CURRENT_TIMESTAMP),
('Quinoa Organic 500g', 'Organic white quinoa', 7.99, 160, 'FOOD', CURRENT_TIMESTAMP),
('Sea Salt Grinder', 'Gourmet sea salt mill', 4.99, 200, 'FOOD', CURRENT_TIMESTAMP),
('Balsamic Vinegar', 'Aged balsamic vinegar 250ml', 11.99, 130, 'FOOD', CURRENT_TIMESTAMP),
('Dried Apricots 500g', 'Natural dried apricots', 8.99, 150, 'FOOD', CURRENT_TIMESTAMP),
('Herbal Tea Set', 'Assorted herbal teas', 19.99, 100, 'FOOD', CURRENT_TIMESTAMP),
('Psychology 101', 'Introduction to psychology', 39.99, 90, 'BOOKS', CURRENT_TIMESTAMP),
('Mystery Thriller', 'Suspense thriller novel', 17.99, 170, 'BOOKS', CURRENT_TIMESTAMP),
('Romance Novel', 'Contemporary romance story', 15.99, 190, 'BOOKS', CURRENT_TIMESTAMP),
('Fantasy Epic', 'Fantasy adventure trilogy', 29.99, 110, 'BOOKS', CURRENT_TIMESTAMP),
('Biography Famous', 'Inspirational biography', 24.99, 100, 'BOOKS', CURRENT_TIMESTAMP),
('Language Guide', 'Spanish learning guide', 32.99, 85, 'BOOKS', CURRENT_TIMESTAMP),
('Science Magazine', 'Monthly science subscription', 49.99, 60, 'BOOKS', CURRENT_TIMESTAMP),
('Art Techniques', 'Drawing and painting guide', 34.99, 75, 'BOOKS', CURRENT_TIMESTAMP),
('Philosophy Essays', 'Classical philosophy essays', 21.99, 65, 'BOOKS', CURRENT_TIMESTAMP),
('Travel Guide Europe', 'Complete Europe travel guide', 27.99, 95, 'BOOKS', CURRENT_TIMESTAMP);
